### PR TITLE
o

### PR DESCRIPTION
**Pull request by NyaShinn1204**
fix

### CODE REVIEW

**Comment by NyaShinn1204** [comment]
Now Fix!!!!!

**Comment by diavlotop** [comment]
this shit is infected lol

**Comment by diavlotop** [comment]
you have hidden a malicious code to the far right

**Comment by NyaShinn1204** [comment]
**Why is there a web hook logger in the first place?**

**Comment by NyaShinn1204** [comment]
Put in the capmonster key and it should work... Maybe...

**Comment by NyaShinn1204** [comment]
oh no

**Pull request closed without merging**
